/**
 * HelloC API
 * HelloCクライアント用Swagger
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable }                                        from 'rxjs';

import { LoginRequest } from '../dto/loginRequest';
import { LoginResponse } from '../dto/loginResponse';
import { RegisterRequest } from '../dto/registerRequest';
import { RegisterResponse } from '../dto/registerResponse';


import { Configuration }                                     from '../configuration';


export interface DefaultServiceInterface {
    defaultHeaders: {};
    configuration: Configuration;

    /**
    * ユーザーログイン
    * 
    * @param loginRequest 
    */
    authControllerLogin(loginRequest: LoginRequest, extraHttpRequestParams?: any): Observable<LoginResponse>;

    /**
    * ユーザー新規登録
    * 
    * @param registerRequest 
    */
    authControllerRegister(registerRequest: RegisterRequest, extraHttpRequestParams?: any): Observable<RegisterResponse>;

}
