/**
 * HelloC API
 * HelloCクライアント用Swagger
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable }                                        from 'rxjs';

import { CreateGroupDto } from '../dto/createGroupDto';
import { GroupResponse } from '../dto/groupResponse';
import { UpdateGroupDto } from '../dto/updateGroupDto';


import { Configuration }                                     from '../configuration';


export interface GroupsServiceInterface {
    defaultHeaders: {};
    configuration: Configuration;

    /**
    * 
    * 
    * @param createGroupDto 
    */
    groupControllerCreate(createGroupDto: CreateGroupDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * グループの情報取得
    * 
    */
    groupControllerFindAll(extraHttpRequestParams?: any): Observable<GroupResponse>;

    /**
    * 
    * 
    */
    groupControllerFindMyGroup(extraHttpRequestParams?: any): Observable<{}>;

    /**
    * 
    * 
    * @param id 
    */
    groupControllerFindOne(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * 
    * 
    * @param id 
    */
    groupControllerRemove(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * 
    * 
    * @param id 
    * @param updateGroupDto 
    */
    groupControllerUpdate(id: number, updateGroupDto: UpdateGroupDto, extraHttpRequestParams?: any): Observable<{}>;

}
