/**
 * HelloC API
 * HelloCクライアント用Swagger
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable }                                        from 'rxjs';

import { CreateLogDto } from '../dto/createLogDto';


import { Configuration }                                     from '../configuration';


export interface LogsServiceInterface {
    defaultHeaders: {};
    configuration: Configuration;

    /**
    * 
    * 
    * @param createLogDto 
    */
    logControllerCreate(createLogDto: CreateLogDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * 
    * 
    * @param id 
    * @param body 
    */
    logControllerCreateDetailLog(id: number, body: object, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * 
    * 
    */
    logControllerFindAll(extraHttpRequestParams?: any): Observable<{}>;

    /**
    * 
    * 
    */
    logControllerFindMyLog(extraHttpRequestParams?: any): Observable<{}>;

    /**
    * 
    * 
    * @param id 
    */
    logControllerFindOne(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * 
    * 
    * @param id 
    */
    logControllerRemove(id: string, extraHttpRequestParams?: any): Observable<{}>;

}
