/**
 * HelloC API
 * HelloCクライアント用Swagger
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable }                                        from 'rxjs';

import { CreateCodingQuestionDto } from '../dto/createCodingQuestionDto';
import { CreateQuestionDto } from '../dto/createQuestionDto';
import { UpdateCodingQuestionDto } from '../dto/updateCodingQuestionDto';
import { UpdateQuestionDto } from '../dto/updateQuestionDto';


import { Configuration }                                     from '../configuration';


export interface QuestionsServiceInterface {
    defaultHeaders: {};
    configuration: Configuration;

    /**
    * 
    * 
    * @param createQuestionDto 
    */
    questionControllerCreate(createQuestionDto: CreateQuestionDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * 
    * 
    * @param id 
    * @param createCodingQuestionDto 
    */
    questionControllerCreateDetailQuestion(id: number, createCodingQuestionDto: CreateCodingQuestionDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * 
    * 
    * @param id 
    * @param detailQuestionId 
    */
    questionControllerDeleteDetailQuestion(id: number, detailQuestionId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * 
    * 
    */
    questionControllerFindAll(extraHttpRequestParams?: any): Observable<{}>;

    /**
    * 
    * 
    */
    questionControllerFindMyQuestion(extraHttpRequestParams?: any): Observable<{}>;

    /**
    * 
    * 
    * @param id 
    */
    questionControllerFindOne(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * 
    * 
    * @param id 
    */
    questionControllerRemove(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * 
    * 
    * @param id 
    * @param updateQuestionDto 
    */
    questionControllerUpdate(id: number, updateQuestionDto: UpdateQuestionDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * 
    * 
    * @param id 
    * @param detailQuestionId 
    * @param updateCodingQuestionDto 
    */
    questionControllerUpdateDetailQuestion(id: number, detailQuestionId: number, updateCodingQuestionDto: UpdateCodingQuestionDto, extraHttpRequestParams?: any): Observable<{}>;

}
