/**
 * HelloC API
 * HelloCクライアント用Swagger
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateQuestionDto { 
    name: string;
    format: string;
    userId: number;
    mode: string;
    timeLimit?: number;
    numberLimit?: number;
}

