/**
 * HelloC API
 * HelloCクライアント用Swagger
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateCodingQuestionDto { 
    questionId: number;
    explain: string;
    language: string;
    baseCode?: string;
    stdinout?: object;
    maxExecTime: number;
    modelAnswer: string;
    judgeFormat: string;
    mandatoryWords?: string;
    miniLines: number;
}

