/**
 * HelloC API
 * HelloCクライアント用Swagger
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GroupResponse { 
    /**
     * グループ名
     */
    name: string;
    /**
     * グループの説明
     */
    summary: string;
    /**
     * アクセスキー
     */
    accessKey: string;
    /**
     * 登録したユーザのid
     */
    userId: number;
}

