/**
 * HelloC API
 * HelloCクライアント用Swagger
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterRequest { 
    /**
     * ユーザー名
     */
    name: string;
    /**
     * メールアドレス
     */
    email: string;
    /**
     * パスワード
     */
    password: string;
    /**
     * 権限
     */
    role: string;
}

